const CHANGE_USERNAME = 'CHANGE_USERNAME';
const CHANGE_CONTENT = 'CHANGE_CONTENT';
const INIT_COMMENTS = 'INIT_COMMENTS';
const ADD_COMMENT = 'ADD_COMMENT';
const DELETE_COMMENT = 'DELETE_COMMENT';

export { CHANGE_USERNAME, CHANGE_CONTENT, INIT_COMMENTS, ADD_COMMENT, DELETE_COMMENT };
